CREATE TABLE invitation
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                     BIGINT,
    event_id                    BIGINT,
    send_date                   TIMESTAMP WITHOUT TIME ZONE,
    response_date               TIMESTAMP WITHOUT TIME ZONE,
    invitation_response_type_id BIGINT,
    CONSTRAINT pk_invitation PRIMARY KEY (id)
);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_INVITATIONRESPONSETYPE
        FOREIGN KEY (invitation_response_type_id) REFERENCES invitation_response_type (id);

CREATE TABLE invitation_response_type
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    response_type VARCHAR(255),
    CONSTRAINT pk_invitationresponsetype PRIMARY KEY (id)
);