


CREATE TABLE invitation_response_type
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    response_type VARCHAR(255),
    CONSTRAINT pk_invitationresponsetype PRIMARY KEY (id)
);



CREATE TABLE event_invite
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   UUID                                    NOT NULL,
    event_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_eventinvite PRIMARY KEY (id)
);

CREATE TABLE user_invite
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    user_name VARCHAR(255),
    CONSTRAINT pk_userinvite PRIMARY KEY (id)
);


CREATE TABLE invitation
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id                    BIGINT,
    user_id                     BIGINT,
    send_by_id                  BIGINT,
    send_date                   TIMESTAMP WITHOUT TIME ZONE,
    response_date               TIMESTAMP WITHOUT TIME ZONE,
    invitation_response_type_id BIGINT,
    CONSTRAINT pk_invitation PRIMARY KEY (id)
);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_EVENT FOREIGN KEY (event_id) REFERENCES event_invite (id);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_INVITATIONRESPONSETYPE FOREIGN KEY (invitation_response_type_id) REFERENCES invitation_response_type (id);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_SEND_BY FOREIGN KEY (send_by_id) REFERENCES user_invite (id);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_USER FOREIGN KEY (user_id) REFERENCES user_invite (id);