CREATE TABLE "user"
(
    uuid       UUID NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    bio        VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (uuid)
);
CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);
CREATE TABLE user_role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_uuid UUID,
    role_id   BIGINT,
    CONSTRAINT pk_userrole PRIMARY KEY (id)
);

ALTER TABLE user_role
    ADD CONSTRAINT FK_USERROLE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT FK_USERROLE_ON_USER_UUID FOREIGN KEY (user_uuid) REFERENCES "user" (uuid);

