CREATE TABLE review
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    event_id  UUID,
    comment   VARCHAR(255),
    timestamp BYTEA,
    rate      SMALLINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);