ALTER TABLE review
    ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE
        USING CASE
                  WHEN timestamp IS NULL THEN NULL
                  ELSE (CAST(timestamp AS TEXT))::TIMESTAMP WITH TIME ZONE
        END;
CREATE TABLE review
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    event_id  UUID,
    comment   VARCHAR(255),
    timestamp BYTEA,
    rate      SMALLINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);