CREATE TABLE event
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255),
    description           VARCHAR(255),
    creation_date         TIMESTAMP WITHOUT TIME ZONE,
    creator_id            BIGINT,
    registration_end_date TIMESTAMP WITHOUT TIME ZONE,
    start_date            TIMESTAMP WITHOUT TIME ZONE,
    end_date              TIMESTAMP WITHOUT TIME ZONE,
    capacity              INTEGER                                 NOT NULL,
    price                 DOUBLE PRECISION                        NOT NULL,
    status_id             BIGINT,
    event_category_id     BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_agends
(
    agends_id BIGINT NOT NULL,
    event_id  BIGINT NOT NULL,
    CONSTRAINT pk_event_agends PRIMARY KEY (agends_id, event_id)
);

ALTER TABLE event_agends
    ADD CONSTRAINT uc_event_agends_agends UNIQUE (agends_id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_EVENTCATEGORY FOREIGN KEY (event_category_id) REFERENCES event_category (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_STATUS FOREIGN KEY (status_id) REFERENCES event_status (id);

ALTER TABLE event_agends
    ADD CONSTRAINT fk_eveage_on_agenda FOREIGN KEY (agends_id) REFERENCES agenda (id);

ALTER TABLE event_agends
    ADD CONSTRAINT fk_eveage_on_event FOREIGN KEY (event_id) REFERENCES event (id);

CREATE TABLE event_status
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_eventstatus PRIMARY KEY (id)
);

CREATE TABLE event_category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_eventcategory PRIMARY KEY (id)
);
CREATE TABLE agenda
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id    BIGINT,
    location_id BIGINT,
    CONSTRAINT pk_agenda PRIMARY KEY (id)
);

ALTER TABLE agenda
    ADD CONSTRAINT FK_AGENDA_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE agenda
    ADD CONSTRAINT FK_AGENDA_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);
CREATE TABLE location
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    longitude VARCHAR(255),
    latitude  VARCHAR(255),
    CONSTRAINT pk_location PRIMARY KEY (id)
);